mkdir -p "videos-selected"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Rosca Direta.mp4" "videos-selected/roscadireta.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Rosca Scott.mp4" "videos-selected/roscascott.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Rosca Unilateral de Costas para Polia.mp4" "videos-selected/roscaunilateraldecostasparapolia.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Manguito Rotador.mp4" "videos-selected/manguitorotador.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Supino Máquina.mp4" "videos-selected/supinomaquina.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Cross Over Embaixo.mp4" "videos-selected/crossoverembaixo.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Crucifixo Máquina.mp4" "videos-selected/crucifixomaquina.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Tríceps Pulley com Corda.mp4" "videos-selected/tricepspulleycomcorda.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Tríceps Francês Unilateral.mp4" "videos-selected/tricepsfrancesunilateral.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Pulley frente.mp4" "videos-selected/pulleyfrente.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/REMADA DO LALÁ!!!.mp4" "videos-selected/remadadolala.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Pulley Frente Supinado ou Fechado.mp4" "videos-selected/pulleyfrentesupinadooufechado.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Crucifixo Inverso na Máquina.mp4" "videos-selected/crucifixoinversonamaquina.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Agachamento Livre.mp4" "videos-selected/agachamentolivre.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Leg Press 45 graus.mp4" "videos-selected/legpress45graus.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Cadeira Extensora.mp4" "videos-selected/cadeiraextensora.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Panturrilha Em Pé.mp4" "videos-selected/panturrilhaempe.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Panturrilha Sentado.mp4" "videos-selected/panturrilhasentado.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Panturrilha no Leg Press.mp4" "videos-selected/panturrilhanolegpress.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Mesa Flexora.mp4" "videos-selected/mesaflexora.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Cadeira Flexora.mp4" "videos-selected/cadeiraflexora.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Stiff.mp4" "videos-selected/stiff.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Elevação diagonal.mp4" "videos-selected/elevacaodiagonal.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Elevação Lateral Unilateral na Polia Média.mp4" "videos-selected/elevacaolateralunilateralnapoliamedia.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Elevação Lateral Máquina.mp4" "videos-selected/elevacaolateralmaquina.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Pulley Frente com Triângulo.mp4" "videos-selected/pulleyfrentecomtriangulo.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Dumbbell Press Reto.mp4" "videos-selected/dumbbellpressreto.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Pullover.mp4" "videos-selected/pullover.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Rosca Simultânea.mp4" "videos-selected/roscasimultanea.mp4"
cp "/Users/guilhermeloureiro/Downloads/TREINO - GUILHERME/EXERCICIOS/Abdominal Máquina.mp4" "videos-selected/abdominalmaquina.mp4"