UPDATE exercises SET video_filename = 'roscadireta.mp4' WHERE name = 'Rosca direta';
UPDATE exercises SET video_filename = 'roscascott.mp4' WHERE name = 'Rosca Scott máquina';
UPDATE exercises SET video_filename = 'roscaunilateraldecostasparapolia.mp4' WHERE name = 'Rosca unilateral de costas';
UPDATE exercises SET video_filename = 'manguitorotador.mp4' WHERE name = 'Manguito rotador';
UPDATE exercises SET video_filename = 'supinomaquina.mp4' WHERE name = 'Supino máquina';
UPDATE exercises SET video_filename = 'crossoverembaixo.mp4' WHERE name = 'Cross over em baixo';
UPDATE exercises SET video_filename = 'crucifixomaquina.mp4' WHERE name = 'Crucifixo máquina';
UPDATE exercises SET video_filename = 'tricepspulleycomcorda.mp4' WHERE name = 'Tríceps pulley com corda';
UPDATE exercises SET video_filename = 'tricepsfrancesunilateral.mp4' WHERE name = 'Tríceps Francês unilateral';
UPDATE exercises SET video_filename = 'pulleyfrente.mp4' WHERE name = 'Pulley frente';
UPDATE exercises SET video_filename = 'remadadolala.mp4' WHERE name = 'Remada do Lalá';
UPDATE exercises SET video_filename = 'pulleyfrentesupinadooufechado.mp4' WHERE name = 'Pulley frente supinado';
UPDATE exercises SET video_filename = 'crucifixoinversonamaquina.mp4' WHERE name = 'Crucifixo inverso na máquina';
UPDATE exercises SET video_filename = 'agachamentolivre.mp4' WHERE name = 'Agachamento livre';
UPDATE exercises SET video_filename = 'legpress45graus.mp4' WHERE name = 'Leg press';
UPDATE exercises SET video_filename = 'cadeiraextensora.mp4' WHERE name = 'Cadeira extensora';
UPDATE exercises SET video_filename = 'panturrilhaempe.mp4' WHERE name = 'Panturrilha em pé';
UPDATE exercises SET video_filename = 'panturrilhasentado.mp4' WHERE name = 'Panturrilha sentado';
UPDATE exercises SET video_filename = 'panturrilhanolegpress.mp4' WHERE name = 'Panturrilha no Leg press';
UPDATE exercises SET video_filename = 'mesaflexora.mp4' WHERE name = 'Mesa Flexora';
UPDATE exercises SET video_filename = 'cadeiraflexora.mp4' WHERE name = 'Cadeira Flexora';
UPDATE exercises SET video_filename = 'stiff.mp4' WHERE name = 'Stiff';
UPDATE exercises SET video_filename = 'elevacaodiagonal.mp4' WHERE name = 'Elevação diagonal';
UPDATE exercises SET video_filename = 'elevacaolateralunilateralnapoliamedia.mp4' WHERE name = 'Elevação lateral unilateral na polia média';
UPDATE exercises SET video_filename = 'elevacaolateralmaquina.mp4' WHERE name = 'Elevação lateral máquina';
UPDATE exercises SET video_filename = 'pulleyfrentecomtriangulo.mp4' WHERE name = 'Pulley frente com triângulo';
UPDATE exercises SET video_filename = 'dumbbellpressreto.mp4' WHERE name = 'Dumbbell press reto';
UPDATE exercises SET video_filename = 'pullover.mp4' WHERE name = 'Pull over';
UPDATE exercises SET video_filename = 'roscasimultanea.mp4' WHERE name = 'Rosca simultânea';
UPDATE exercises SET video_filename = 'abdominalmaquina.mp4' WHERE name = 'Abdominal máquina';